In [2]:
import numpy as np


In [8]:
x = np.arange(21)
x_2 = x[10:21]
print(x_2)

[10 11 12 13 14 15 16 17 18 19 20]


In [9]:
print(x_2[::-1])

[20 19 18 17 16 15 14 13 12 11 10]


In [10]:
x_22 = np.array([[0,1],[2,3]])
print(x_22)

[[0 1]
 [2 3]]


In [11]:
x_44 = np.random.randint(10 , size = ( 4 , 4, 4))
print(x_44)

[[[7 3 4 4]
  [4 4 0 0]
  [2 7 5 0]
  [8 1 5 3]]

 [[7 0 3 3]
  [4 1 7 1]
  [4 8 0 7]
  [7 8 5 1]]

 [[9 4 8 0]
  [1 5 0 7]
  [3 5 6 5]
  [5 2 0 0]]

 [[9 4 9 1]
  [4 2 0 9]
  [2 9 6 9]
  [1 2 0 4]]]


In [14]:
x_33 = np.random.randint(10 , size = (3 , 3))
max_value = np.max(x_33)
min_value = np.min(x_33)
print(f"max: {max_value}")
print(f"min: {min_value}")

max: 9
min: 1


In [5]:
chessboard = np.zeros((8 , 8) , dtype = int)

chessboard[1::2 , ::2] = 1
chessboard[::2, 1::2 ] = 1

print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [10]:
x_7 = np.array([ 1 , -2 , 1 , 6 , -9 , 8 , -6 , 5])
x_7[x_7 < 0] = -x_7[x_7 < 0]

max_value = np.max(x_7)
print(f"Max: {max_value}")

x_7[x_7 == max_value] = 0
print(f"upd: {x_7}")

Max: 9
upd: [1 2 1 6 0 8 6 5]


In [20]:
x_8 = np.random.randint(10 , size = (4 , 4))
print(x_8)

print()

print(x_8[:2, :3])
print()

print(x_8[:, 1:2])
print()

x_8[: , 1] = 100
print(x_8) 
print()

x_8 = np.copy(x_8[: , 1::2])
x_8[:,0] = 50
print(x_8)

[[0 4 6 7]
 [7 9 7 5]
 [7 2 0 1]
 [9 7 9 0]]

[[0 4 6]
 [7 9 7]]

[[4]
 [9]
 [2]
 [7]]

[[  0 100   6   7]
 [  7 100   7   5]
 [  7 100   0   1]
 [  9 100   9   0]]

[[50  7]
 [50  5]
 [50  1]
 [50  0]]


In [29]:
x_9_1 = np.random.randint(10 , size = (3 , 3))
x_9_2 = np.random.randint(10 , size = (3 , 3))


np.concatenate([x_9_1 , x_9_2] , axis = 1)


array([[2, 1, 9, 1, 3, 5],
       [7, 7, 3, 8, 5, 6],
       [5, 7, 3, 6, 8, 3]])

In [31]:
np.concatenate([x_9_1 , x_9_2] , axis = 0)

array([[2, 1, 9],
       [7, 7, 3],
       [5, 7, 3],
       [1, 3, 5],
       [8, 5, 6],
       [6, 8, 3]])

In [32]:
np.vstack([x_9_1 , x_9_2])

array([[2, 1, 9],
       [7, 7, 3],
       [5, 7, 3],
       [1, 3, 5],
       [8, 5, 6],
       [6, 8, 3]])

In [33]:
np.hstack([x_9_1 , x_9_2])

array([[2, 1, 9, 1, 3, 5],
       [7, 7, 3, 8, 5, 6],
       [5, 7, 3, 6, 8, 3]])

In [35]:
x_10 = np.random.randint( 10 , size = (6 , 6))

first_half_horizontal = x_10[:3, :]
second_half_horizontal = x_10[3: , :]

print(first_half_horizontal)
print()
print(second_half_horizontal)
print()

first_half_vertical = x_10[:, :3]
second_half_vertical = x_10[: , 3:]

print(first_half_vertical)
print()

print(second_half_vertical)


[[9 1 3 3 7 3]
 [9 9 3 8 4 0]
 [2 0 0 6 2 8]]

[[0 5 8 3 0 6]
 [6 6 5 4 3 7]
 [0 0 7 8 4 4]]

[[9 1 3]
 [9 9 3]
 [2 0 0]
 [0 5 8]
 [6 6 5]
 [0 0 7]]

[[3 7 3]
 [8 4 0]
 [6 2 8]
 [3 0 6]
 [4 3 7]
 [8 4 4]]


'\n# Разбиваем массив по вертикали пополам\nfirst_half_vertical = arr[:, :3]\nsecond_half_vertical = arr[:, 3:]\n\n# Выводим результат\nprint("\nПервый (вертикально):\n", first_half_vertical)\nprint("\nВторой (вертикально):\n", second_half_vertical)\n\n\n'